"""Update Migration

Revision ID: fb7ee7e36084
Revises: c9da18eccb4c
Create Date: 2022-05-12 22:26:49.616035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7ee7e36084'
down_revision = 'c9da18eccb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downvotes', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'downvotes', 'pitches', ['pitch_id'], ['id'])
    op.add_column('upvotes', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'upvotes', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_column('upvotes', 'pitch_id')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.drop_column('downvotes', 'pitch_id')
    # ### end Alembic commands ###
